/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#707972",
        "on-tertiary-fixed": "#191e00",
        "surface-variant": "#a6f5a3",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#bdf378",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#bfc9c0",
        "on-tertiary-container": "#bcca76",
        "tertiary-fixed": "#dcea93",
        "on-tertiary-fixed-variant": "#414c03",
        "on-secondary-fixed": "#102000",
        "on-background": "#002105",
        "on-surface-variant": "#404942",
        "on-secondary": "#ffffff",
        "secondary-container": "#baf076",
        "on-surface": "#002105",
        "error-container": "#ffdad6",
        "surface-container-high": "#acfba8",
        "background": "#ebffe5",
        "primary-fixed-dim": "#90d5ae",
        "inverse-surface": "#00390d",
        "secondary": "#416900",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed": "#abf2c9",
        "surface-tint": "#256a4a",
        "surface-container-highest": "#a6f5a3",
        "surface": "#ebffe5",
        "secondary-fixed-dim": "#a2d65f",
        "surface-container-low": "#d4ffce",
        "on-secondary-fixed-variant": "#2f4f00",
        "on-primary-container": "#8bd1a9",
        "on-primary-fixed": "#002112",
        "surface-bright": "#ebffe5",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#005234",
        "primary-container": "#105b3c",
        "surface-dim": "#9eed9b",
        "on-secondary-container": "#446e00",
        "tertiary-container": "#4a550d",
        "on-error-container": "#93000a",
        "inverse-primary": "#90d5ae",
        "surface-container": "#baffb5",
        "tertiary": "#343d00",
        "tertiary-fixed-dim": "#c0ce7a",
        "inverse-on-surface": "#c8ffc2",
        "primary": "#004229",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "1.5rem",
        xl: "2.25rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "80px",
        "container-padding-mobile": "20px",
        "base": "8px",
        "gutter": "24px",
        "container-padding-desktop": "80px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Poppins"],
        "title-md": ["Poppins"],
        "headline-lg": ["Poppins"],
        "display-lg": ["Poppins"],
        "body-lg": ["Poppins"],
        "body-md": ["Poppins"],
        "label-sm": ["Poppins"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
